sudo: required
services:
  - docker

before_install:
  - docker build -t vishanuel/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true vishanuel/docker-react npm run test -- --coverage